name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # This workflow triggers on pushes to the main branch

jobs:
  build_site:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Check out the repository

      - name: Install Node.js
        uses: actions/setup-node@v4  # Setup Node.js
        with:
          node-version: 20  # Use Node.js version 20
          cache: npm  # Cache npm dependencies

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"  # Set base path for routing
        run: |
          npm run build  # Run the build script

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3  # Upload the built files
        with:
          path: "build/"  # Path to the build output
          
  deploy:
    needs: build_site  # Ensure this job runs after build_site
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner
    permissions:
      pages: write  # Permissions to write to GitHub pages
      id-token: write  # Permissions for ID token

    environment:
      name: github-pages  # Name of the environment
      url: ${{ steps.deployment.outputs.page_url }}  # URL of the deployed site

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4  # Use the deploy-pages action to deploy